//
//  CountryList.swift
//  Sell Factory
//
//  Created by Pranav Badgi on 7/2/21.
//

import Foundation
import UIKit


//MARK: - Struct
struct COUNTRY {
    //A
    static let Andorra = "🇦🇩 Andorra"
    static let UnitedArabEmirates = "🇦🇪 United Arab Emirates"
    static let Afghanistan = "🇦🇫 Afghanistan"
    static let AntiguaandBarbuda = "🇦🇬 Antigua and Barbuda"
    static let Anguilla = "🇦🇮 Anguilla"
    static let Albania = "🇦🇱 Albania"
    static let Armenia = "🇦🇲Armenia"
    static let Angola = "🇦🇴 Angola"
    static let Antarctica = "🇦🇶 Antarctica"
    static let Argentina = "🇦🇷 Argentina"
    static let AmericanSamoa = "🇦🇸 American Samoa"
    static let Austria = "🇦🇹 Austria"
    static let Australia = "🇦🇺 Australia"
    static let Aruba = "🇦🇼 Aruba"
    static let ÅlandIslands = "🇦🇽 Åland Islands"
    static let Azerbaijan = "🇦🇿 Azerbaijan"
    //B
    static let BosniaandHerzegovina = "🇧🇦 Bosnia and Herzegovina"
    static let Barbados = "🇧🇧 Barbados"
    static let Bangladesh = "🇧🇩 Bangladesh"
    static let Belgium = "🇧🇪 Belgium"
    static let BurkinaFaso = "🇧🇫 Burkina Faso"
    static let Bulgaria = "🇧🇬 Bulgaria"
    static let Bahrain = "🇧🇭 Bahrain"
    static let Burundi = "🇧🇮 Burundi"
    static let Benin = "🇧🇯 Benin"
    static let SaintBarthélemy = "🇧🇱 Saint Barthélemy"
    static let Bermuda = "🇧🇲 Bermuda"
    static let BruneiDarussalam = "🇧🇳 Brunei Darussalam"
    static let Bolivia = "🇧🇴 Bolivia"
    static let BonaireSintEustatiusandSaba = "🇧🇶 Bonaire, Sint Eustatius and Saba"
    static let Brazil = "🇧🇷 Brazil"
    static let Bahamas = "🇧🇸 Bahamas"
    static let Bhutan = "🇧🇹 Bhutan"
    static let BouvetIsland = "🇧🇻 Bouvet Island"
    static let Botswana = "🇧🇼 Botswana"
    static let Belarus = "🇧🇾 Belarus"
    static let Belize = "🇧🇿 Belize"
    //C
    static let Canada = "🇨🇦 Canada"
    static let CocosKeelingIslands = "🇨🇨 Cocos (Keeling) Islands"
    static let Congo = "🇨🇩 Congo"
    static let CentralAfricanRepublic = "🇨🇫 Central African Republic"
    static let Congo2 = "🇨🇬 Congo"
    static let Switzerland = "🇨🇭 Switzerland"
    static let CôteDIvoire = "🇨🇮 Côte D'Ivoire"
    static let CookIslands = "🇨🇰 Cook Islands"
    static let Chile = "🇨🇱 Chile"
    static let Cameroon = "🇨🇲 Cameroon"
    static let China = "🇨🇳 China"
    static let Colombia = "🇨🇴 Colombia"
    static let CostaRica = "🇨🇷 Costa Rica"
    static let Cuba = "🇨🇺 Cuba"
    static let CapeVerde = "🇨🇻 Cape Verde"
    static let Curaçao = "🇨🇼 Curaçao"
    static let ChristmasIsland = "🇨🇽 Christmas Island"
    static let Cyprus = "🇨🇾 Cyprus"
    static let CzechRepublic = "🇨🇿 Czech Republic"
    //D
    static let Germany = "🇩🇪 Germany"
    static let Djibouti = "🇩🇯 Djibouti"
    static let Denmark = "🇩🇰 Denmark"
    static let Dominica = "🇩🇲 Dominica"
    static let DominicanRepublic = "🇩🇴 Dominican Republic"
    static let Algeria = "🇩🇿 Algeria"
    //E
    static let Ecuador = "🇪🇨 Ecuador"
    static let Estonia = "🇪🇪 Estonia"
    static let Egypt = "🇪🇬 Egypt"
    static let WesternSahara = "🇪🇭 Western Sahara"
    static let Eritrea = "🇪🇷 Eritrea"
    static let Spain = "🇪🇸 Spain"
    static let Ethiopia = "🇪🇹 Ethiopia"
    //F
    static let Finland = "🇫🇮 Finland"
    static let Fiji = "🇫🇯 Fiji"
    static let FalklandIslandsMalvinas = "🇫🇰 Falkland Islands (Malvinas)"
    static let Micronesia = "🇫🇲 Micronesia"
    static let FaroeIslands = "🇫🇴 Faroe Islands"
    static let France = "🇫🇷 France"
    //G
    static let Gabon = "🇬🇦 Gabon"
    static let UnitedKingdom = "🇬🇧 United Kingdom"
    static let Grenada = "🇬🇩 Grenada"
    static let Georgia = "🇬🇪 Georgia"
    static let FrenchGuiana = "🇬🇫 French Guiana"
    static let Guernsey = "🇬🇬 Guernsey"
    static let Ghana = "🇬🇭 Ghana"
    static let Gibraltar = "🇬🇮 Gibraltar"
    static let Greenland = "🇬🇱 Greenland"
    static let Gambia = "🇬🇲 Gambia"
    static let Guinea = "🇬🇳 Guinea"
    static let Guadeloupe = "🇬🇵 Guadeloupe"
    static let EquatorialGuinea = "🇬🇶 Equatorial Guinea"
    static let Greece = "🇬🇷 Greece"
    static let SouthGeorgia = "🇬🇸 South Georgia"
    static let Guatemala = "🇬🇹 Guatemala"
    static let Guam = "🇬🇺 Guam"
    static let GuineaBissau = "🇬🇼 Guinea-Bissau"
    static let Guyana = "🇬🇾 Guyana"
    //H
    static let HongKong = "🇭🇰 Hong Kong"
    static let HeardIslandandMcdonaldIslands = "🇭🇲 Heard Island and Mcdonald Islands"
    static let Honduras = "🇭🇳 Honduras"
    static let Croatia = "🇭🇷 Croatia"
    static let Haiti = "🇭🇹 Haiti"
    static let Hungary = "🇭🇺 Hungary"
    //I
    static let Indonesia = "🇮🇩 Indonesia"
    static let Ireland = "🇮🇪 Ireland"
    static let Israel = "🇮🇱 Israel"
    static let IsleofMan = "🇮🇲 Isle of Man"
    static let India = "🇮🇳 India"
    static let BritishIndianOceanTerritory = "🇮🇴 British Indian Ocean Territory"
    static let Iraq = "🇮🇶 Iraq"
    static let Iran = "🇮🇷 Iran"
    static let Iceland = "🇮🇸 Iceland"
    static let Italy = "🇮🇹 Italy"
    //J
    static let Jersey = "🇯🇪 Jersey"
    static let Jamaica = "🇯🇲 Jamaica"
    static let Jordan = "🇯🇴 Jordan"
    static let Japan = "🇯🇵 Japan"
    //K
    static let Kenya = "🇰🇪 Kenya"
    static let Kyrgyzstan = "🇰🇬 Kyrgyzstan"
    static let Cambodia = "🇰🇭 Cambodia"
    static let Kiribati = "🇰🇮 Kiribati"
    static let Comoros = "🇰🇲 Comoros"
    static let SaintKittsandNevis = "🇰🇳 Saint Kitts and Nevis"
    static let NorthKorea = "🇰🇵 North Korea"
    static let SouthKorea = "🇰🇷 South Korea"
    static let Kuwait = "🇰🇼 Kuwait"
    static let CaymanIslands = "🇰🇾 Cayman Islands"
    static let Kazakhstan = "🇰🇿 Kazakhstan"
    //L
    static let LaoPeopleDemocraticRepublic = "🇱🇦 Lao People's Democratic Republic"
    static let Lebanon = "🇱🇧 Lebanon"
    static let SaintLucia = "🇱🇨 Saint Lucia"
    static let Liechtenstein = "🇱🇮 Liechtenstein"
    static let SriLanka = "🇱🇰 Sri Lanka"
    static let Liberia = "🇱🇷 Liberia"
    static let Lesotho = "🇱🇸 Lesotho"
    static let Lithuania = "🇱🇹 Lithuania"
    static let Luxembourg = "🇱🇺 Luxembourg"
    static let Latvia = "🇱🇻 Latvia"
    static let Libya = "🇱🇾 Libya"
    //M
    static let Morocco = "🇲🇦 Morocco"
    static let Monaco = "🇲🇨 Monaco"
    static let Moldova = "🇲🇩 Moldova"
    static let Montenegro = "🇲🇪 Montenegro"
    static let SaintMartinFrenchPart = "🇲🇫 Saint Martin (French Part)"
    static let Madagascar = "🇲🇬 Madagascar"
    static let MarshallIslands = "🇲🇭 Marshall Islands"
    static let Macedonia = "🇲🇰 Macedonia"
    static let Mali = "🇲🇱 Mali"
    static let Myanmar = "🇲🇲 Myanmar"
    static let Mongolia = "🇲🇳 Mongolia"
    static let Macao = "🇲🇴 Macao"
    static let NorthernMarianaIslands = "🇲🇵 Northern Mariana Islands"
    static let Martinique = "🇲🇶 Martinique"
    static let Mauritania = "🇲🇷 Mauritania"
    static let Montserrat = "🇲🇸 Montserrat"
    static let Malta = "🇲🇹 Malta"
    static let Mauritius = "🇲🇺 Mauritius"
    static let Maldives = "🇲🇻 Maldives"
    static let Malawi = "🇲🇼 Malawi"
    static let Mexico = "🇲🇽 Mexico"
    static let Malaysia = "🇲🇾 Malaysia"
    static let Mozambique = "🇲🇿 Mozambique"
    //N
    static let Namibia = "🇳🇦 Namibia"
    static let NewCaledonia = "🇳🇨 New Caledonia"
    static let Niger = "🇳🇪 Niger"
    static let NorfolkIsland = "🇳🇫 Norfolk Island"
    static let Nigeria = "🇳🇬 Nigeria"
    static let Nicaragua = "🇳🇮 Nicaragua"
    static let Netherlands = "🇳🇱 Netherlands"
    static let Norway = "🇳🇴 Norway"
    static let Nepal = "🇳🇵 Nepal"
    static let Nauru = "🇳🇷 Nauru"
    static let Niue = "🇳🇺 Niue"
    static let NewZealand = "🇳🇿 New Zealand"
    //O
    static let Oman = "🇴🇲 Oman"
    //P
    static let Panama = "🇵🇦 Panama"
    static let Peru = "🇵🇪 Peru"
    static let FrenchPolynesia = "🇵🇫 French Polynesia"
    static let PapuaNewGuinea = "🇵🇬 Papua New Guinea"
    static let Philippines = "🇵🇭 Philippines"
    static let Pakistan = "🇵🇰 Pakistan"
    static let Poland = "🇵🇱 Poland"
    static let SaintPierreandMiquelon = "🇵🇲 Saint Pierre and Miquelon"
    static let Pitcairn = "🇵🇳 Pitcairn"
    static let PuertoRico = "🇵🇷 Puerto Rico"
    static let PalestinianTerritory = "🇵🇸 Palestinian Territory"
    static let Portugal = "🇵🇹 Portugal"
    static let Palau = "🇵🇼 Palau"
    static let Paraguay = "🇵🇾 Paraguay"
    //Q
    static let Qatar = "🇶🇦 Qatar"
    //R
    static let Réunion = "🇷🇪 Réunion"
    static let Romania = "🇷🇴 Romania"
    static let Serbia = "🇷🇸 Serbia"
    static let Russia = "🇷🇺 Russia"
    static let Rwanda = "🇷🇼 Rwanda"
    //S
    static let SaudiArabia = "🇸🇦 Saudi Arabia"
    static let SolomonIslands = "🇸🇧 Solomon Islands"
    static let Seychelles = "🇸🇨 Seychelles"
    static let Sudan = "🇸🇩 Sudan"
    static let Sweden = "🇸🇪 Sweden"
    static let Singapore = "🇸🇬 Singapore"
    static let SaintHelenaAscensionTristanDaCunha = "🇸🇭 Saint Helena, Ascension and Tristan Da Cunha"
    static let Slovenia = "🇸🇮 Slovenia"
    static let SvalbardandJanMayen = "🇸🇯 Svalbard and Jan Mayen"
    static let Slovakia = "🇸🇰 Slovakia"
    static let SierraLeone = "🇸🇱 Sierra Leone"
    static let SanMarino = "🇸🇲 San Marino"
    static let Senegal = "🇸🇳 Senegal"
    static let Somalia = "🇸🇴 Somalia"
    static let Suriname = "🇸🇷 Suriname"
    static let SouthSudan = "🇸🇸 South Sudan"
    static let SaoTomeandPrincipe = "🇸🇹 Sao Tome and Principe"
    static let ElSalvador = "🇸🇻 El Salvador"
    static let SintMaartenDutchPart = "🇸🇽 Sint Maarten (Dutch Part)"
    static let SyrianArabRepublic = "🇸🇾 Syrian Arab Republic"
    static let Swaziland = "🇸🇿 Swaziland"
    //T
    static let TurksandCaicosIslands = "🇹🇨 Turks and Caicos Islands"
    static let Chad = "🇹🇩 Chad"
    static let FrenchSouthernTerritories = "🇸🇳 French Southern Territories"
    static let Togo = "🇹🇬 Togo"
    static let Thailand = "🇹🇭 Thailand"
    static let Tajikistan = "🇹🇯 Tajikistan"
    static let Tokelau = "🇹🇰 Tokelau"
    static let TimorLeste = "🇹🇱 Timor-Leste"
    static let Turkmenistan = "🇹🇲 Turkmenistan"
    static let Tunisia = "🇹🇳 Tunisia"
    static let Tonga = "🇹🇴 Tonga"
    static let Turkey = "🇹🇷 Turkey"
    static let TrinidadandTobago = "🇹🇹 Trinidad and Tobago"
    static let Tuvalu = "🇹🇻 Tuvalu"
    static let Taiwan = "🇹🇼 Taiwan"
    static let Tanzania = "🇹🇿 Tanzania"
    //U
    static let Ukraine = "🇺🇦 Ukraine"
    static let Uganda = "🇺🇬 Uganda"
    static let UnitedStatesMinorOutlyingIslands = "🇺🇲 United States Minor Outlying Islands"
    static let UnitedStates = "🇺🇲 United States"
    static let Uruguay = "🇺🇾 Uruguay"
    static let Uzbekistan = "🇺🇿 Uzbekistan"
    //V
    static let VaticanCity = "🇺🇾 Vatican City"
    static let SaintVincentandTheGrenadines = "🇺🇾 Saint Vincent and The Grenadines"
    static let Venezuela = "🇺🇾 Venezuela"
    static let VirginIslandsBritish = "🇺🇾 Virgin Islands, British"
    static let VirginIslandsUS = "🇺🇾 Virgin Islands, U.S."
    static let VietNam = "🇺🇾 Viet Nam"
    static let Vanuatu = "🇺🇾 Vanuatu"
    //
    static let WallisandFutuna = "🇼🇫 Wallis and Futuna"
    static let Samoa = "🇼🇸 Samoa"
    static let Yemen = "🇾🇪 Yemen"
    static let Mayotte = "🇾🇹 Mayotte"
    static let SouthAfrica = "🇿🇦 South Africa"
    static let Zambia = "🇿🇲 Zambia"
    static let Zimbabwe = "🇿🇼 Zimbabwe"
    
}


//MARK: - Array
let countryListArray = [COUNTRY.Andorra, COUNTRY.UnitedArabEmirates, COUNTRY.Afghanistan, COUNTRY.AntiguaandBarbuda, COUNTRY.Anguilla,
                        COUNTRY.Albania, COUNTRY.Armenia, COUNTRY.Angola, COUNTRY.Antarctica, COUNTRY.Argentina, COUNTRY.AmericanSamoa,
                        COUNTRY.Austria, COUNTRY.Australia, COUNTRY.Aruba, COUNTRY.ÅlandIslands, COUNTRY.Azerbaijan, COUNTRY.BosniaandHerzegovina,
                        COUNTRY.Barbados, COUNTRY.Bangladesh, COUNTRY.Belgium, COUNTRY.BurkinaFaso, COUNTRY.Bulgaria,
                        COUNTRY.Bahrain, COUNTRY.Burundi, COUNTRY.Benin, COUNTRY.SaintBarthélemy, COUNTRY.Bermuda, COUNTRY.BruneiDarussalam, COUNTRY.Bolivia, COUNTRY.BonaireSintEustatiusandSaba, COUNTRY.Brazil, COUNTRY.Bahamas, COUNTRY.Bhutan, COUNTRY.BouvetIsland, COUNTRY.Botswana, COUNTRY.Belarus, COUNTRY.Belize, COUNTRY.Canada, COUNTRY.CocosKeelingIslands, COUNTRY.Congo, COUNTRY.CentralAfricanRepublic, COUNTRY.Congo2, COUNTRY.Switzerland, COUNTRY.CôteDIvoire, COUNTRY.CookIslands, COUNTRY.Chile, COUNTRY.Cameroon, COUNTRY.China, COUNTRY.Colombia, COUNTRY.CostaRica, COUNTRY.Cuba, COUNTRY.CapeVerde, COUNTRY.Curaçao, COUNTRY.ChristmasIsland, COUNTRY.Cyprus, COUNTRY.CzechRepublic, COUNTRY.Germany, COUNTRY.Djibouti, COUNTRY.Denmark, COUNTRY.Dominica, COUNTRY.DominicanRepublic, COUNTRY.Algeria, COUNTRY.Ecuador, COUNTRY.Estonia, COUNTRY.Egypt, COUNTRY.WesternSahara, COUNTRY.Eritrea, COUNTRY.Spain, COUNTRY.Ethiopia, COUNTRY.Finland, COUNTRY.Fiji, COUNTRY.FalklandIslandsMalvinas, COUNTRY.Micronesia, COUNTRY.FaroeIslands, COUNTRY.France, COUNTRY.Gabon, COUNTRY.UnitedKingdom, COUNTRY.Grenada, COUNTRY.Georgia, COUNTRY.FrenchGuiana, COUNTRY.Guernsey, COUNTRY.Ghana, COUNTRY.Gibraltar, COUNTRY.Greenland, COUNTRY.Gambia, COUNTRY.Guinea, COUNTRY.Guadeloupe, COUNTRY.EquatorialGuinea, COUNTRY.Greece, COUNTRY.SouthGeorgia, COUNTRY.Guatemala, COUNTRY.Guam, COUNTRY.GuineaBissau, COUNTRY.Guyana, COUNTRY.HongKong, COUNTRY.HeardIslandandMcdonaldIslands, COUNTRY.Honduras, COUNTRY.Croatia, COUNTRY.Haiti, COUNTRY.Hungary, COUNTRY.Indonesia, COUNTRY.Ireland, COUNTRY.Israel, COUNTRY.IsleofMan, COUNTRY.India, COUNTRY.BritishIndianOceanTerritory, COUNTRY.Iraq, COUNTRY.Iran, COUNTRY.Iceland, COUNTRY.Italy, COUNTRY.Jersey, COUNTRY.Jamaica, COUNTRY.Jordan, COUNTRY.Japan, COUNTRY.Kenya, COUNTRY.Kyrgyzstan, COUNTRY.Cambodia, COUNTRY.Kiribati, COUNTRY.Comoros, COUNTRY.SaintKittsandNevis, COUNTRY.NorthKorea, COUNTRY.SouthKorea, COUNTRY.Kuwait, COUNTRY.CaymanIslands, COUNTRY.Kazakhstan, COUNTRY.LaoPeopleDemocraticRepublic, COUNTRY.Lebanon, COUNTRY.SaintLucia, COUNTRY.Liechtenstein, COUNTRY.SriLanka, COUNTRY.Liberia, COUNTRY.Lesotho, COUNTRY.Lithuania, COUNTRY.Luxembourg, COUNTRY.Latvia, COUNTRY.Libya, COUNTRY.Morocco, COUNTRY.Monaco, COUNTRY.Moldova, COUNTRY.Montenegro, COUNTRY.SaintMartinFrenchPart, COUNTRY.Madagascar, COUNTRY.MarshallIslands, COUNTRY.Macedonia, COUNTRY.Mali, COUNTRY.Myanmar, COUNTRY.Mongolia, COUNTRY.Macao, COUNTRY.NorthernMarianaIslands, COUNTRY.Martinique, COUNTRY.Mauritania, COUNTRY.Montserrat, COUNTRY.Malta, COUNTRY.Mauritius, COUNTRY.Maldives, COUNTRY.Malawi, COUNTRY.Mexico, COUNTRY.Mozambique, COUNTRY.Namibia, COUNTRY.NewCaledonia, COUNTRY.Niger, COUNTRY.NorfolkIsland, COUNTRY.Nigeria, COUNTRY.Nicaragua, COUNTRY.Netherlands, COUNTRY.Norway, COUNTRY.Nepal, COUNTRY.Nauru, COUNTRY.Niue, COUNTRY.NewZealand, COUNTRY.Oman, COUNTRY.Panama, COUNTRY.Peru, COUNTRY.FrenchPolynesia,COUNTRY.PapuaNewGuinea, COUNTRY.Philippines, COUNTRY.Pakistan, COUNTRY.Poland, COUNTRY.SaintPierreandMiquelon, COUNTRY.Pitcairn, COUNTRY.PuertoRico, COUNTRY.PalestinianTerritory, COUNTRY.Portugal, COUNTRY.Palau, COUNTRY.Paraguay, COUNTRY.Qatar, COUNTRY.Réunion, COUNTRY.Romania, COUNTRY.Serbia, COUNTRY.Russia, COUNTRY.Rwanda, COUNTRY.SaudiArabia, COUNTRY.SolomonIslands, COUNTRY.Seychelles, COUNTRY.Sudan, COUNTRY.Sweden, COUNTRY.Singapore, COUNTRY.SaintHelenaAscensionTristanDaCunha, COUNTRY.Slovenia, COUNTRY.SvalbardandJanMayen, COUNTRY.Slovakia, COUNTRY.SierraLeone, COUNTRY.SanMarino, COUNTRY.Senegal, COUNTRY.Somalia, COUNTRY.Suriname, COUNTRY.SouthSudan, COUNTRY.SaoTomeandPrincipe, COUNTRY.ElSalvador, COUNTRY.SintMaartenDutchPart, COUNTRY.SyrianArabRepublic, COUNTRY.Swaziland, COUNTRY.TurksandCaicosIslands, COUNTRY.Chad, COUNTRY.FrenchSouthernTerritories, COUNTRY.Togo, COUNTRY.Thailand, COUNTRY.Tajikistan, COUNTRY.Tokelau, COUNTRY.TimorLeste, COUNTRY.Turkmenistan, COUNTRY.Tunisia, COUNTRY.Tonga, COUNTRY.Turkey, COUNTRY.TrinidadandTobago, COUNTRY.Tuvalu, COUNTRY.Taiwan, COUNTRY.Tanzania, COUNTRY.Ukraine, COUNTRY.Uganda, COUNTRY.UnitedStatesMinorOutlyingIslands, COUNTRY.UnitedStates, COUNTRY.Uruguay, COUNTRY.Uzbekistan,
                        COUNTRY.VaticanCity, COUNTRY.SaintVincentandTheGrenadines, COUNTRY.Venezuela, COUNTRY.VirginIslandsBritish, COUNTRY.VirginIslandsUS, COUNTRY.VietNam, COUNTRY.Vanuatu, COUNTRY.WallisandFutuna, COUNTRY.Samoa, COUNTRY.Yemen, COUNTRY.Mayotte, COUNTRY.SouthAfrica, COUNTRY.Zambia, COUNTRY.Zimbabwe]
